name: "CI"

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:

  Testing:
    name: "PHP Checks"
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build test runner
      uses: docker/build-push-action@v5
      with:
        push: false
        target: test-runner
        tags: php${{ matrix.php-version }}-checks
        build-args: PHP_VERSION=${{ matrix.php-version }}
    - name: Run tests
      run: docker run --rm -v ./:/var/www/html php${{ matrix.php-version }}-checks sh -c "composer test:all"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
